# Generated by Django 4.2.20 on 2025-04-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newject', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
