# Generated by Django 4.2.20 on 2025-04-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newject', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='sermons/audio/'),
        ),
    ]
