# Generated by Django 4.2.20 on 2025-04-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newject', '0004_alter_sermon_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='audio_file',
        ),
    ]
